#配置建立数据库连接参数
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/eesy_mybatis?serverTimezone=UTC&useUnicode=true&characterEncodeing=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis ：
#  type-aliases-package：实体类所在的包路径
#  mapper-locations： mapper配置文件所在的路径，注意classpath：后面不加/表示resources路径下
mybatis:
  type-aliases-package: com.itguigu.webtest.pojo
  mapper-locations:  classpath:mybatis/mapper/*.xml
